import type { Metadata } from "next";
import { Inter, Dangrek } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation"

const inter = Inter({ subsets: ["latin"] });
const myfont = Dangrek({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={myfont.className}>
                <Navigation />
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
